import type { CalcExpectedQuantityRead, CalcPassportSummaryRead } from '@quantor/api-client';

/** Синтетика экрана «Расчёты → ВК» — как её отдаёт сервер PROMPT 06. Числа не инженерные. */

const base = (
  overrides: Partial<CalcExpectedQuantityRead> & Pick<CalcExpectedQuantityRead, 'quantity_key'>,
): CalcExpectedQuantityRead => ({
  id: overrides.quantity_key,
  passport_id: 'passport-1',
  system_code: 'В1',
  discipline: 'VK',
  scope: { building: '1', discipline: 'VK', system_code: 'В1' },
  scenario: 'TENDER_SAFE',
  category: 'PIPE',
  item_type: 'RISER_PIPE',
  title: 'Трубы стояков',
  function: 'VERTICAL',
  attributes: {},
  material: null,
  size: null,
  amount: {},
  unit: 'm',
  base: null,
  reserve: null,
  completeness: 'BLOCKED',
  derivation: 'NOT_DETERMINED',
  aggregate: false,
  calculation_run_id: null,
  synthesis_run_id: null,
  element_ids: [],
  result_keys: [],
  rule_refs: [],
  assumptions: [],
  warnings: [],
  blocked_by: [],
  components: [],
  notice: null,
  explanation: '',
  ...overrides,
});

export const volumeRows = (): CalcExpectedQuantityRead[] => [
  base({
    quantity_key: 'vk.b1.pipe.riser',
    amount: { low: '146.4', high: '219.6' },
    base: { low: '144.4', high: '216.6' },
    reserve: {
      rule_key: 'vk.tender.riser_length_reserve',
      version: 1,
      amount: { low: '2', high: '3' },
      unit: 'm',
      reason: 'Сценарий TENDER_SAFE допускает тендерные допущения',
      impact: 'Длина больше на резерв',
    },
    completeness: 'RANGE',
    derivation: 'CALCULATED',
    components: [
      {
        key: 'interfloor',
        title: 'Межэтажная часть на стояк',
        amount: { value: '70.2' },
        unit: 'm',
        known: true,
      },
    ],
    notice: 'Это не норматив и не факт документации. Это тендерное допущение.',
  }),
  base({
    quantity_key: 'vk.b1.pipe.main',
    title: 'Трубы магистрали',
    item_type: 'MAIN_PIPE',
    blocked_by: ['main.route'],
    explanation: 'трасса не определена — длина не выдумывается',
  }),
  base({
    quantity_key: 'vk.b1.pipe.total',
    title: 'Трубопроводы системы — итог',
    item_type: 'PIPE_TOTAL',
    aggregate: true,
    amount: { low: '236.4', high: '458.1' },
    completeness: 'PARTIAL',
    derivation: 'AGGREGATE',
    blocked_by: ['main.route'],
    explanation: 'Подтверждаемая часть: 236,4–458,1 м. Полная длина пока не определена',
  }),
  base({
    quantity_key: 'vk.b1.fitting.branch',
    title: 'Ответвления (тройники) на присоединении подключений',
    category: 'FITTING',
    item_type: 'BRANCH_TEE',
    unit: 'piece',
    amount: { low: '46', high: '69' },
    completeness: 'RANGE',
    derivation: 'TOPOLOGY',
  }),
];

export const passportSummary = (): CalcPassportSummaryRead => ({
  id: 'passport-1',
  batch_id: 'batch-1',
  project_id: 'project-1',
  system_code: 'В1',
  system_title: 'Хозяйственно-питьевой водопровод',
  scope: { building: '1', discipline: 'VK', system_code: 'В1' },
  status: 'PARTIAL',
  calculator_id: 'vk.b1.stage_p',
  calculator_version: 1,
  synthesizer_id: 'vk.b1.structure',
  synthesizer_version: 1,
  quantities_count: 51,
  highlights: ['Стояки: 2–3 — не выбрано', 'Трубы магистрали: не определено'],
  problems: ['Правил, ожидающих инженера: 11'],
  passport_sha256: 'a'.repeat(64),
  created_by: null,
  created_at: '2026-09-28T12:00:00Z',
});
