// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminJobRead
 *
 * Задание в эксплуатационном виде.
 *
 * Отдельно от `JobRead`: пользователю не нужны попытки и исполнитель, а администратору
 * без них не разобрать, почему задание висит. Полезная нагрузка сюда не попадает —
 * в ней лежат идентификаторы и пути, а не то, что стоит показывать целиком.
 */
export type AdminJobRead = {
    /**
     * Attempt
     */
    attempt: number;
    /**
     * Available At
     */
    available_at: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Heartbeat At
     */
    heartbeat_at: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Retryable
     */
    is_retryable: boolean;
    job_type: JobType;
    /**
     * Lease Expires At
     */
    lease_expires_at: string | null;
    /**
     * Max Attempts
     */
    max_attempts: number;
    /**
     * Progress
     */
    progress: number | null;
    /**
     * Project Id
     */
    project_id: string | null;
    scope: JobScope;
    /**
     * Stage
     */
    stage: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    status: JobStatus;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Worker Id
     */
    worker_id: string | null;
    /**
     * Workspace Id
     */
    workspace_id: string | null;
};

/**
 * ArtifactKind
 *
 * Роль файла внутри распознанного пакета.
 */
export type ArtifactKind = 'blocks_json' | 'results_md' | 'results_html' | 'package_zip' | 'other';

/**
 * AuditEventRead
 *
 * Запись журнала. Только чтение: операций изменения у журнала нет вовсе.
 */
export type AuditEventRead = {
    /**
     * Action
     */
    action: string;
    /**
     * Actor Label
     */
    actor_label: string | null;
    /**
     * Actor Role
     */
    actor_role: string | null;
    /**
     * After Summary
     */
    after_summary: {
        [key: string]: unknown;
    } | null;
    /**
     * Before Summary
     */
    before_summary: {
        [key: string]: unknown;
    } | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Request Id
     */
    request_id: string | null;
    /**
     * Resource Id
     */
    resource_id: string | null;
    /**
     * Resource Type
     */
    resource_type: string;
    result: AuditResult;
    /**
     * Workspace Id
     */
    workspace_id: string | null;
};

/**
 * AuditResult
 *
 * Чем закончилось действие.
 *
 * Отказ записывается наравне с успехом: попытка сделать то, на что нет прав, —
 * это ровно то событие, ради которого журнал и заводят.
 */
export type AuditResult = 'success' | 'failure' | 'denied';

/**
 * Body_upload_file
 */
export type BodyUploadFile = {
    /**
     * Document Id
     *
     * Добавить как новую ревизию существующего документа
     */
    document_id?: string | null;
    /**
     * File
     *
     * Файл проекта
     */
    file: Blob | File;
};

/**
 * ComponentDiagnosticsRead
 *
 * Состояние одного компонента установки.
 *
 * `source` показывается рядом со статусом намеренно: «в порядке» без ответа на вопрос
 * «когда и откуда это известно» — половина сведений.
 */
export type ComponentDiagnosticsRead = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Duration Ms
     */
    duration_ms?: number | null;
    /**
     * Facts
     */
    facts?: {
        [key: string]: string;
    };
    /**
     * Name
     */
    name: string;
    /**
     * Remediation
     */
    remediation?: string | null;
    source: ProbeSource;
    status: ProbeStatus;
    /**
     * Title
     */
    title: string;
};

/**
 * ComponentHealth
 */
export type ComponentHealth = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Name
     */
    name: string;
    /**
     * Required
     */
    required?: boolean;
    /**
     * Status
     */
    status: 'ok' | 'degraded' | 'unavailable' | 'outdated';
};

/**
 * ContentUrl
 *
 * Ссылка на файл ревизии прямо из хранилища.
 *
 * API не проксирует бинарные данные: документ на 50–500 МБ не должен проходить через
 * процесс приложения (ADR-0002).
 */
export type ContentUrl = {
    /**
     * Content Type
     */
    content_type: string;
    /**
     * Expires In
     */
    expires_in: number;
    /**
     * Filename
     */
    filename: string;
    /**
     * Url
     */
    url: string;
};

/**
 * DataPolicy
 *
 * Куда позволено уходить данным.
 *
 * Для проектной документации это бывает жёстким требованием заказчика, а не
 * пожеланием: чертёж объекта нельзя отправлять наружу ни при каких условиях.
 */
export type DataPolicy = 'local_only' | 'remote_allowed' | 'restricted_data';

/**
 * DiagnosticsReport
 *
 * Сводка по установке. Итог считается по обязательным компонентам.
 */
export type DiagnosticsReport = {
    /**
     * Components
     */
    components: Array<ComponentDiagnosticsRead>;
    /**
     * Generated At
     */
    generated_at: string;
    status: ProbeStatus;
};

/**
 * DocumentKind
 *
 * Природа документа. BIM-форматы принимаются на хранение, но не разбираются.
 */
export type DocumentKind = 'pdf' | 'recognized_package' | 'revit' | 'navisworks' | 'ifc' | 'other';

/**
 * DocumentRead
 */
export type DocumentRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Discipline
     */
    discipline: string | null;
    /**
     * Display Name
     */
    display_name: string;
    document_kind: DocumentKind;
    /**
     * Id
     */
    id: string;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * DocumentRevisionRead
 */
export type DocumentRevisionRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Geometry Error Code
     */
    geometry_error_code: string | null;
    geometry_status: GeometryStatus;
    /**
     * Id
     */
    id: string;
    /**
     * Processing Error Code
     */
    processing_error_code: string | null;
    processing_status: ProcessingStatus;
    /**
     * Revision Label
     */
    revision_label: string | null;
    /**
     * Source Filename
     */
    source_filename: string;
    /**
     * Source Metadata
     */
    source_metadata: {
        [key: string]: unknown;
    };
    /**
     * Source Mime
     */
    source_mime: string;
    /**
     * Source Sha256
     */
    source_sha256: string;
    /**
     * Source Size
     */
    source_size: number;
};

/**
 * FlagOverrideWrite
 */
export type FlagOverrideWrite = {
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Reason
     */
    reason?: string | null;
    scope: OverrideScope;
};

/**
 * FlagStateRead
 *
 * Флаг вместе с тем, откуда взялось его значение и можно ли его трогать.
 */
export type FlagStateRead = {
    /**
     * Admin Editable
     */
    admin_editable: boolean;
    /**
     * Default
     */
    default: boolean;
    /**
     * Description
     */
    description: string;
    /**
     * Effective
     */
    effective: boolean;
    /**
     * Follows Configuration
     */
    follows_configuration: boolean;
    /**
     * Key
     */
    key: string;
    /**
     * Reason
     */
    reason: string;
    source: ValueSource;
    /**
     * Stage
     */
    stage: string;
    /**
     * Title
     */
    title: string;
    /**
     * Workspace Scoped
     */
    workspace_scoped: boolean;
};

/**
 * GeometryStatus
 *
 * Состояние извлечения канонической геометрии страниц ревизии.
 *
 * Относится ко всей ревизии, а не к отдельной странице: если число страниц в PDF не
 * совпало с числом листов, доверять нельзя ни одной. Частично извлечённой геометрии не
 * бывает (ADR-0016).
 *
 * Отдельно от `ProcessingStatus`: тот описывает импорт распознанного пакета и у обычного
 * PDF навсегда остаётся `unprocessed`. Одно поле на два независимых процесса означало бы,
 * что успех одного стирает отказ другого.
 */
export type GeometryStatus = 'not_applicable' | 'pending' | 'extracting' | 'ready' | 'failed';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobRead
 */
export type JobRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Id
     */
    id: string;
    job_type: JobType;
    /**
     * Progress
     */
    progress: number | null;
    /**
     * Project Id
     */
    project_id: string | null;
    /**
     * Stage
     */
    stage: string | null;
    /**
     * Started At
     */
    started_at: string | null;
    status: JobStatus;
};

/**
 * JobScope
 *
 * Кому принадлежит задание.
 *
 * Это словарь контракта, а не колонка: область выводится из пары `workspace_id`/`project_id`
 * у `Job`. Отдельная колонка была бы производной от той же пары и однажды разошлась бы с ней.
 *
 * `system` — обслуживание установки. Такое задание не видно ни одному рабочему пространству
 * и доступно только через административный контур.
 */
export type JobScope = 'system' | 'workspace' | 'project';

/**
 * JobStatsRead
 *
 * Счётчики очереди для панели обзора.
 */
export type JobStatsRead = {
    /**
     * Failed Recently
     */
    failed_recently: number;
    /**
     * Queued
     */
    queued: number;
    /**
     * Running
     */
    running: number;
    /**
     * Workers Alive
     */
    workers_alive: number;
    /**
     * Workers Total
     */
    workers_total: number;
};

/**
 * JobStatus
 */
export type JobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

/**
 * JobType
 *
 * Типы заданий.
 *
 * Реальны legacy_import и pdf_geometry_extract. Остальные объявлены как контракт и
 * не исполняются.
 */
export type JobType = 'legacy_import' | 'pdf_geometry_extract';

/**
 * LengthUnit
 *
 * Единица, в которой человек вводит известный размер.
 *
 * Внутренний канон — миллиметр: именно в нём проставлены размеры на строительных
 * чертежах. Введённое значение сохраняется вместе с единицей — как доказательство
 * того, что именно набрал человек.
 */
export type LengthUnit = 'mm' | 'cm' | 'm';

/**
 * LivenessResponse
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * LogoutResponse
 *
 * Результат выхода. Повторный выход не ошибка — сеанса уже нет.
 */
export type LogoutResponse = {
    /**
     * Ok
     */
    ok?: boolean;
};

/**
 * MetaResponse
 */
export type MetaResponse = {
    /**
     * Api Version
     */
    api_version: string;
    /**
     * Auth Mode
     */
    auth_mode: 'dev' | 'oidc';
    /**
     * Environment
     */
    environment: string;
    /**
     * Features
     */
    features: {
        [key: string]: boolean;
    };
    /**
     * Schema Version
     */
    schema_version: number;
    /**
     * Stage
     */
    stage: string;
};

/**
 * ModelProviderProbeRead
 *
 * Результат явной проверки связи. Задержка появляется только здесь и только по кнопке.
 */
export type ModelProviderProbeRead = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Latency Ms
     */
    latency_ms: number;
    /**
     * Provider Id
     */
    provider_id: string;
    /**
     * Status
     */
    status: 'healthy' | 'unavailable';
};

/**
 * ModelProviderRead
 *
 * Поставщик моделей в административном виде.
 *
 * Поля под значение ключа здесь нет. Наружу уходит имя переменной окружения и признак
 * «задана» — маскировать нечего там, где нечего показывать (промт 07).
 */
export type ModelProviderRead = {
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Credential Configured
     */
    credential_configured: boolean | null;
    /**
     * Credential Env
     */
    credential_env: string | null;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Endpoint Label
     */
    endpoint_label: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Usable
     */
    is_usable: boolean;
    kind: ProviderKind;
    /**
     * Max Concurrency
     */
    max_concurrency: number;
    /**
     * Models
     */
    models: Array<ModelSpecRead>;
    /**
     * Name
     */
    name: string;
    policy: DataPolicy;
    /**
     * Runs Locally
     */
    runs_locally: boolean;
    /**
     * Timeout Seconds
     */
    timeout_seconds: number;
};

/**
 * ModelSpecRead
 *
 * Одна модель у поставщика.
 */
export type ModelSpecRead = {
    /**
     * Capabilities
     */
    capabilities: Array<string>;
    /**
     * Context Tokens
     */
    context_tokens: number;
    /**
     * Max Output Tokens
     */
    max_output_tokens: number;
    /**
     * Model Id
     */
    model_id: string;
};

/**
 * OverrideScope
 *
 * Уровень, на котором переопределяется настройка или флаг.
 *
 * `PROJECT` объявлен, но ни одной настройке пока не разрешён: контракт готов к
 * расширению, а выдавать несуществующий уровень за работающий нельзя. Тест следит,
 * чтобы уровень не появился в определениях раньше, чем в коде, который его читает.
 */
export type OverrideScope = 'system' | 'workspace' | 'project';

/**
 * PageGeometryRead
 *
 * Каноническая геометрия страницы (ADR-0016).
 *
 * Пространство `pdf_display_points_top_left`: точка PDF, начало в левом верхнем углу,
 * поворот **уже учтён** в отображаемых размерах. Поэтому перевод из нормализованных
 * координат — умножение, без повторного поворота.
 *
 * Размеры и рамки передаются строками: `JSON.parse` превращает число в float64, и
 * каноническая десятичная запись, на которой построен отпечаток, теряется.
 */
export type PageGeometryRead = {
    /**
     * Coordinate Space
     */
    coordinate_space: string;
    /**
     * Crop Box
     */
    crop_box: Array<string>;
    /**
     * Display Height Pt
     */
    display_height_pt: string;
    /**
     * Display Width Pt
     */
    display_width_pt: string;
    /**
     * Extracted At
     */
    extracted_at: string;
    /**
     * Geometry Fingerprint
     */
    geometry_fingerprint: string;
    /**
     * Media Box
     */
    media_box: Array<string>;
    /**
     * Parser Name
     */
    parser_name: string;
    /**
     * Parser Version
     */
    parser_version: string;
    /**
     * Pdf Rotation
     */
    pdf_rotation: number;
    /**
     * Sheet Id
     */
    sheet_id: string;
    /**
     * Source Sha256
     */
    source_sha256: string;
};

/**
 * Page[AdminJobRead]
 */
export type PageAdminJobRead = {
    /**
     * Items
     */
    items: Array<AdminJobRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[AuditEventRead]
 */
export type PageAuditEventRead = {
    /**
     * Items
     */
    items: Array<AuditEventRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[DocumentRead]
 */
export type PageDocumentRead = {
    /**
     * Items
     */
    items: Array<DocumentRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[DocumentRevisionRead]
 */
export type PageDocumentRevisionRead = {
    /**
     * Items
     */
    items: Array<DocumentRevisionRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[JobRead]
 */
export type PageJobRead = {
    /**
     * Items
     */
    items: Array<JobRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[ProjectSummary]
 */
export type PageProjectSummary = {
    /**
     * Items
     */
    items: Array<ProjectSummary>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[RegionRead]
 */
export type PageRegionRead = {
    /**
     * Items
     */
    items: Array<RegionRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * Page[SheetRead]
 */
export type PageSheetRead = {
    /**
     * Items
     */
    items: Array<SheetRead>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
    /**
     * Total
     */
    total: number;
};

/**
 * ProbeSource
 *
 * Откуда взялось состояние. Показывается рядом с ним — иначе непонятно, насколько свежее.
 */
export type ProbeSource = 'live' | 'reported' | 'config' | 'unknown';

/**
 * ProbeStatus
 */
export type ProbeStatus = 'healthy' | 'degraded' | 'unavailable' | 'not_configured' | 'unknown';

/**
 * ProcessingStatus
 *
 * Состояние обработки конкретной ревизии.
 *
 * Единственное изменяемое поле ревизии: описывает не файл, а ход работы над ним.
 */
export type ProcessingStatus = 'pending' | 'unprocessed' | 'processor_unavailable' | 'importing' | 'ready' | 'failed';

/**
 * ProjectCreate
 */
export type ProjectCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ProjectJobSummary
 *
 * Состояние последнего задания проекта.
 *
 * Компактнее полного JobRead: список проектов не должен тащить служебные поля,
 * которые в нём всё равно не показать.
 */
export type ProjectJobSummary = {
    /**
     * Error Code
     */
    error_code: string | null;
    /**
     * Finished At
     */
    finished_at: string | null;
    /**
     * Id
     */
    id: string;
    job_type: JobType;
    /**
     * Progress
     */
    progress: number | null;
    /**
     * Stage
     */
    stage: string | null;
    status: JobStatus;
};

/**
 * ProjectRead
 */
export type ProjectRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * External Ref
     */
    external_ref: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    source: ProjectSource;
    status: ProjectStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectSort
 */
export type ProjectSort = 'recent' | 'name';

/**
 * ProjectSource
 *
 * Откуда взялся проект.
 *
 * Нужен, чтобы отличить заведённый руками проект от подтянутого из внешней системы:
 * у второго есть чужой идентификатор, и повторно создавать его нельзя.
 */
export type ProjectSource = 'manual' | 'tenderhub';

/**
 * ProjectStatus
 *
 * Жизненный цикл проекта. Ход импорта сюда не пишется — он живёт в Job и ревизиях.
 */
export type ProjectStatus = 'active' | 'archived';

/**
 * ProjectSummary
 *
 * Проект вместе с производными счётчиками — то, что нужно списку и карточке.
 *
 * Последнее задание отдаётся здесь же: иначе, чтобы увидеть ход импорта, пришлось бы
 * открывать каждый проект по очереди.
 */
export type ProjectSummary = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Document Count
     */
    document_count: number;
    /**
     * External Ref
     */
    external_ref: string | null;
    /**
     * Id
     */
    id: string;
    last_job?: ProjectJobSummary | null;
    /**
     * Name
     */
    name: string;
    /**
     * Sheet Count
     */
    sheet_count: number;
    source: ProjectSource;
    status: ProjectStatus;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * ProjectUpdate
 */
export type ProjectUpdate = {
    /**
     * Name
     */
    name?: string | null;
    status?: ProjectStatus | null;
};

/**
 * ProviderKind
 *
 * Как разговаривать с поставщиком.
 *
 * Различие протокольное, а не маркетинговое: vLLM, SGLang и LM Studio отвечают
 * OpenAI-совместимым API, и адаптер у них будет общий.
 */
export type ProviderKind = 'openai_compatible' | 'anthropic_compatible' | 'lm_studio' | 'vllm' | 'sglang' | 'custom';

/**
 * ReadinessResponse
 */
export type ReadinessResponse = {
    /**
     * Components
     */
    components: Array<ComponentHealth>;
    /**
     * Schema Revision
     */
    schema_revision: string;
    /**
     * Status
     */
    status: 'ok' | 'degraded';
};

/**
 * RecognitionArtifactRead
 */
export type RecognitionArtifactRead = {
    artifact_kind: ArtifactKind;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Id
     */
    id: string;
    /**
     * Metadata
     */
    metadata: {
        [key: string]: unknown;
    };
    /**
     * Revision Id
     */
    revision_id: string;
    /**
     * Schema Version
     */
    schema_version: number | null;
    /**
     * Sha256
     */
    sha256: string;
    /**
     * Source Filename
     */
    source_filename: string;
};

/**
 * RegionRead
 *
 * Область распознавания.
 *
 * coords_norm — [x0, y0, x1, y1] от левого верхнего угла листа, значения в [0, 1].
 * Перевод в экранные координаты выполняет клиент при отрисовке (ADR-0008).
 */
export type RegionRead = {
    /**
     * Block Type
     */
    block_type: string;
    /**
     * Coords Norm
     */
    coords_norm: Array<number>;
    /**
     * External Block Id
     */
    external_block_id: string;
    /**
     * Id
     */
    id: string;
    /**
     * Legacy Metadata
     */
    legacy_metadata: {
        [key: string]: unknown;
    };
    /**
     * Ordinal
     */
    ordinal: number | null;
    /**
     * Polygon Points
     */
    polygon_points: Array<Array<number>> | null;
    /**
     * Raw Content Md
     */
    raw_content_md: string | null;
    /**
     * Recognition Status
     */
    recognition_status: string | null;
    shape_type: RegionShape;
    /**
     * Sheet Id
     */
    sheet_id: string;
};

/**
 * RegionShape
 */
export type RegionShape = 'rectangle' | 'polygon';

/**
 * Role
 *
 * Роль — именованный набор разрешений, а не проверяемая сущность.
 *
 * Бизнес-код спрашивает разрешение (`Permission`), а не имя роли: состав набора меняется
 * в одном месте, а не по всем обработчикам. Соответствие описано в `app/auth/permissions.py`.
 *
 * `PLATFORM_ADMIN` и `SERVICE` относятся к платформе и живут на самой личности; остальные
 * выдаются членством в конкретном рабочем пространстве.
 */
export type Role = 'platform_admin' | 'workspace_admin' | 'engineer' | 'reviewer' | 'viewer' | 'service';

/**
 * ScaleCalibrationCreate
 *
 * Запрос на ручную калибровку.
 *
 * Коэффициент сюда не передаётся и не принимается: его считает сервер из точек и
 * канонической геометрии страницы. Иначе величину можно было бы задать запросом.
 */
export type ScaleCalibrationCreate = {
    /**
     * Known Distance
     */
    known_distance: number | string;
    /**
     * Make Default
     */
    make_default?: boolean;
    /**
     * Point A
     */
    point_a: [
        number | string,
        number | string
    ];
    /**
     * Point B
     */
    point_b: [
        number | string,
        number | string
    ];
    /**
     * Supersedes Id
     */
    supersedes_id?: string | null;
    unit?: LengthUnit;
};

/**
 * ScaleCalibrationRead
 *
 * Калибровка масштаба листа (ADR-0018).
 *
 * Числа передаются строками: `JSON.parse` превратил бы их в float64 и потерял точную
 * десятичную запись, по которой калибровку проверяют.
 */
export type ScaleCalibrationRead = {
    /**
     * Created At
     */
    created_at: string;
    /**
     * Created By
     */
    created_by: string | null;
    /**
     * Id
     */
    id: string;
    input_unit: LengthUnit;
    /**
     * Input Value
     */
    input_value: string;
    /**
     * Is Default
     */
    is_default: boolean;
    /**
     * Known Distance Mm
     */
    known_distance_mm: string;
    /**
     * Mm Per Pt
     */
    mm_per_pt: string;
    /**
     * Page Distance Pt
     */
    page_distance_pt: string;
    /**
     * Page Geometry Fingerprint
     */
    page_geometry_fingerprint: string;
    /**
     * Point A X
     */
    point_a_x: string;
    /**
     * Point A Y
     */
    point_a_y: string;
    /**
     * Point B X
     */
    point_b_x: string;
    /**
     * Point B Y
     */
    point_b_y: string;
    scope_kind: ScaleScopeKind;
    /**
     * Sheet Id
     */
    sheet_id: string;
    source: ScaleSource;
    /**
     * Supersedes Id
     */
    supersedes_id: string | null;
    verification_state: VerificationState;
    /**
     * Verified At
     */
    verified_at: string | null;
    /**
     * Verified By
     */
    verified_by: string | null;
};

/**
 * ScaleScopeKind
 *
 * На что распространяется калибровка.
 *
 * Лист с планом 1:100 и узлом 1:20 — обычное дело, поэтому `region` объявлен сразу.
 * На Stage 2A создаётся только `sheet`, но схема локальный масштаб не запрещает:
 * модель, исходящая из одного масштаба на лист, не пережила бы первый же такой чертёж.
 */
export type ScaleScopeKind = 'sheet' | 'region';

/**
 * ScaleSource
 *
 * Откуда взялся масштаб чертежа.
 *
 * На Stage 2A публичный API создаёт только `manual`. Остальные объявлены как контракт,
 * но записать их через эндпоинт нельзя: иначе ручную калибровку можно было бы выдать
 * за автоматически подтверждённую (ADR-0018).
 */
export type ScaleSource = 'manual' | 'detected_dimension' | 'imported';

/**
 * ScaleVerificationWrite
 *
 * Подтверждение калибровки или снятие подтверждения.
 */
export type ScaleVerificationWrite = {
    state: VerificationState;
};

/**
 * SessionResponse
 *
 * Состояние сеанса.
 *
 * Отдаётся и портале, и админке: обе решают по нему, что показывать. Права перечислены
 * явно — интерфейс не должен знать состав ролей и повторять его у себя.
 */
export type SessionResponse = {
    /**
     * Auth Mode
     */
    auth_mode: 'dev' | 'oidc';
    /**
     * Authenticated
     */
    authenticated: boolean;
    /**
     * Csrf Token
     */
    csrf_token?: string | null;
    /**
     * Permissions
     */
    permissions?: Array<string>;
    role?: Role | null;
    user?: SessionUser | null;
    /**
     * Workspace Id
     */
    workspace_id?: string | null;
    /**
     * Workspaces
     */
    workspaces?: Array<SessionWorkspace>;
};

/**
 * SessionUser
 *
 * Личность текущего сеанса. Ни токенов, ни секретов — только то, что рисует интерфейс.
 */
export type SessionUser = {
    /**
     * Display Name
     */
    display_name: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Is Platform Admin
     */
    is_platform_admin: boolean;
};

/**
 * SessionWorkspace
 *
 * Пространство, доступное пользователю, и его роль в нём.
 */
export type SessionWorkspace = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    role: Role;
    /**
     * Slug
     */
    slug: string;
};

/**
 * SettingOverrideWrite
 */
export type SettingOverrideWrite = {
    scope: OverrideScope;
    /**
     * Value
     */
    value: boolean | number | string | Array<string>;
};

/**
 * SettingStateRead
 *
 * Настройка вместе с действующим значением и его происхождением.
 *
 * Определение и значение в одном ответе намеренно: страница настроек строится из
 * метаданных реестра, а не из зашитой в интерфейс копии списка.
 */
export type SettingStateRead = {
    /**
     * Allowed Scopes
     */
    allowed_scopes: Array<OverrideScope>;
    /**
     * Category
     */
    category: string;
    /**
     * Choices
     */
    choices?: Array<string>;
    /**
     * Default Value
     */
    default_value: boolean | number | string | Array<string>;
    /**
     * Description
     */
    description: string;
    /**
     * Editable
     */
    editable: boolean;
    /**
     * Is Secret
     */
    is_secret: boolean;
    /**
     * Key
     */
    key: string;
    /**
     * Maximum
     */
    maximum?: number | null;
    /**
     * Minimum
     */
    minimum?: number | null;
    /**
     * Restart Required
     */
    restart_required: boolean;
    source: ValueSource;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Updated By
     */
    updated_by?: string | null;
    /**
     * Value
     */
    value: boolean | number | string | Array<string>;
    /**
     * Value Type
     */
    value_type: string;
};

/**
 * SheetRead
 */
export type SheetRead = {
    /**
     * Height Px
     */
    height_px: number | null;
    /**
     * Id
     */
    id: string;
    /**
     * Page Index
     */
    page_index: number;
    /**
     * Page Label
     */
    page_label: string | null;
    /**
     * Region Count
     */
    region_count: number;
    /**
     * Revision Id
     */
    revision_id: string;
    /**
     * Rotation
     */
    rotation: number;
    /**
     * Width Px
     */
    width_px: number | null;
};

/**
 * TenderBindingPreviewRead
 *
 * Предпросмотр перепривязки: что было, что станет и что мешает.
 */
export type TenderBindingPreviewRead = {
    /**
     * Conflicting Project Id
     */
    conflicting_project_id: string | null;
    /**
     * Conflicting Project Name
     */
    conflicting_project_name: string | null;
    /**
     * Current External Id
     */
    current_external_id: string | null;
    /**
     * Current External Ref
     */
    current_external_ref: string | null;
    /**
     * Is Noop
     */
    is_noop: boolean;
    /**
     * Project Id
     */
    project_id: string;
    /**
     * Target Client Name
     */
    target_client_name: string | null;
    /**
     * Target External Id
     */
    target_external_id: string;
    /**
     * Target External Ref
     */
    target_external_ref: string | null;
    /**
     * Target Title
     */
    target_title: string;
};

/**
 * TenderBriefRead
 *
 * Тендер TenderHUB в том виде, в каком его показывает портал.
 *
 * Сметные строки и суммы сюда не входят: портал на Stage 1 не ведёт расчёт, и
 * показывать чужие деньги как свой результат нельзя (границы этапа в CLAUDE.md).
 */
export type TenderBriefRead = {
    /**
     * Client Name
     */
    client_name: string | null;
    /**
     * Construction Scope
     */
    construction_scope: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Imported Project Id
     */
    imported_project_id: string | null;
    /**
     * Submission Deadline
     */
    submission_deadline: string | null;
    /**
     * Tender Number
     */
    tender_number: string | null;
    /**
     * Title
     */
    title: string;
    /**
     * Updated At
     */
    updated_at: string | null;
    /**
     * Version
     */
    version: number | null;
};

/**
 * TenderHubProbeRead
 *
 * Результат явной проверки связи. Выполняется по кнопке, а не при открытии страницы.
 */
export type TenderHubProbeRead = {
    /**
     * Checked At
     */
    checked_at: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Error Code
     */
    error_code?: string | null;
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Tender Count
     */
    tender_count?: number | null;
};

/**
 * TenderHubStatusRead
 *
 * Состояние интеграции. Ключ не показывается ни в каком виде — только факт наличия.
 */
export type TenderHubStatusRead = {
    /**
     * Base Url
     */
    base_url: string;
    /**
     * Configured
     */
    configured: boolean;
    /**
     * Credential State
     */
    credential_state: 'configured' | 'missing';
    /**
     * Linked Project Count
     */
    linked_project_count: number;
};

/**
 * TenderImport
 *
 * Запрос на создание проекта по тендеру.
 */
export type TenderImport = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Tender Id
     */
    tender_id: string;
};

/**
 * TenderRebindRequest
 */
export type TenderRebindRequest = {
    /**
     * Confirm
     */
    confirm?: boolean;
    /**
     * Tender Id
     */
    tender_id: string;
};

/**
 * UploadRead
 *
 * Результат загрузки.
 *
 * is_duplicate означает, что такой файл в проекте уже был: возвращается прежняя ревизия,
 * вторая копия не создаётся.
 */
export type UploadRead = {
    document: DocumentRead;
    /**
     * Is Duplicate
     */
    is_duplicate: boolean;
    job: JobRead | null;
    revision: DocumentRevisionRead;
};

/**
 * UploadedFileType
 *
 * Что портал умеет делать с файлом такого расширения.
 */
export type UploadedFileType = {
    /**
     * Capability
     */
    capability: string;
    document_kind: DocumentKind;
    /**
     * Extension
     */
    extension: string;
    /**
     * Max Size Bytes
     */
    max_size_bytes: number;
    /**
     * Schedules Import
     */
    schedules_import: boolean;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * ValueSource
 *
 * Откуда взялось действующее значение настройки или флага.
 *
 * Показывается администратору вместе со значением: «включено» без ответа на вопрос
 * «кем и где» — это половина сведений, по которой ничего не починить.
 */
export type ValueSource = 'default' | 'system' | 'workspace' | 'deployment';

/**
 * VerificationState
 *
 * Состояние проверки человеком.
 */
export type VerificationState = 'unverified' | 'verified' | 'disputed';

/**
 * WorkerRead
 *
 * Исполнитель заданий. Показывается в эксплуатации, а не пользователю.
 */
export type WorkerRead = {
    /**
     * Current Job Id
     */
    current_job_id: string | null;
    /**
     * Heartbeat At
     */
    heartbeat_at: string;
    /**
     * Host
     */
    host: string;
    /**
     * Id
     */
    id: string;
    /**
     * Is Alive
     */
    is_alive: boolean;
    /**
     * Pid
     */
    pid: number;
    /**
     * Started At
     */
    started_at: string;
    /**
     * Version
     */
    version: string;
};

export type ListAuditEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
        /**
         * Action
         *
         * Фильтр по действию
         */
        action?: string | null;
        /**
         * Resource Type
         *
         * Фильтр по типу объекта
         */
        resource_type?: string | null;
        /**
         * Result
         *
         * Фильтр по результату
         */
        result?: AuditResult | null;
        /**
         * Actor User Id
         *
         * Фильтр по актору
         */
        actor_user_id?: string | null;
        /**
         * Since
         *
         * Не раньше
         */
        since?: string | null;
        /**
         * Until
         *
         * Не позже
         */
        until?: string | null;
    };
    url: '/api/v1/admin/audit';
};

export type ListAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAuditEventsError = ListAuditEventsErrors[keyof ListAuditEventsErrors];

export type ListAuditEventsResponses = {
    /**
     * Successful Response
     */
    200: PageAuditEventRead;
};

export type ListAuditEventsResponse = ListAuditEventsResponses[keyof ListAuditEventsResponses];

export type ReadDiagnosticsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/diagnostics';
};

export type ReadDiagnosticsResponses = {
    /**
     * Successful Response
     */
    200: DiagnosticsReport;
};

export type ReadDiagnosticsResponse = ReadDiagnosticsResponses[keyof ReadDiagnosticsResponses];

export type ListFeatureFlagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/feature-flags';
};

export type ListFeatureFlagsResponses = {
    /**
     * Response List Feature Flags
     *
     * Successful Response
     */
    200: Array<FlagStateRead>;
};

export type ListFeatureFlagsResponse = ListFeatureFlagsResponses[keyof ListFeatureFlagsResponses];

export type DeleteFeatureFlagOverrideData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query: {
        /**
         * С какого уровня снять
         */
        scope: OverrideScope;
    };
    url: '/api/v1/admin/feature-flags/{key}';
};

export type DeleteFeatureFlagOverrideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFeatureFlagOverrideError = DeleteFeatureFlagOverrideErrors[keyof DeleteFeatureFlagOverrideErrors];

export type DeleteFeatureFlagOverrideResponses = {
    /**
     * Successful Response
     */
    200: FlagStateRead;
};

export type DeleteFeatureFlagOverrideResponse = DeleteFeatureFlagOverrideResponses[keyof DeleteFeatureFlagOverrideResponses];

export type SetFeatureFlagOverrideData = {
    body: FlagOverrideWrite;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/v1/admin/feature-flags/{key}';
};

export type SetFeatureFlagOverrideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetFeatureFlagOverrideError = SetFeatureFlagOverrideErrors[keyof SetFeatureFlagOverrideErrors];

export type SetFeatureFlagOverrideResponses = {
    /**
     * Successful Response
     */
    200: FlagStateRead;
};

export type SetFeatureFlagOverrideResponse = SetFeatureFlagOverrideResponses[keyof SetFeatureFlagOverrideResponses];

export type ReadTenderhubStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/integrations/tenderhub';
};

export type ReadTenderhubStatusResponses = {
    /**
     * Successful Response
     */
    200: TenderHubStatusRead;
};

export type ReadTenderhubStatusResponse = ReadTenderhubStatusResponses[keyof ReadTenderhubStatusResponses];

export type RebindTenderhubProjectData = {
    body: TenderRebindRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/admin/integrations/tenderhub/projects/{project_id}/rebind';
};

export type RebindTenderhubProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RebindTenderhubProjectError = RebindTenderhubProjectErrors[keyof RebindTenderhubProjectErrors];

export type RebindTenderhubProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type RebindTenderhubProjectResponse = RebindTenderhubProjectResponses[keyof RebindTenderhubProjectResponses];

export type PreviewTenderhubRebindData = {
    body: TenderRebindRequest;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/admin/integrations/tenderhub/projects/{project_id}/rebind/preview';
};

export type PreviewTenderhubRebindErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PreviewTenderhubRebindError = PreviewTenderhubRebindErrors[keyof PreviewTenderhubRebindErrors];

export type PreviewTenderhubRebindResponses = {
    /**
     * Successful Response
     */
    200: TenderBindingPreviewRead;
};

export type PreviewTenderhubRebindResponse = PreviewTenderhubRebindResponses[keyof PreviewTenderhubRebindResponses];

export type UnlinkTenderhubProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/admin/integrations/tenderhub/projects/{project_id}/unlink';
};

export type UnlinkTenderhubProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UnlinkTenderhubProjectError = UnlinkTenderhubProjectErrors[keyof UnlinkTenderhubProjectErrors];

export type UnlinkTenderhubProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UnlinkTenderhubProjectResponse = UnlinkTenderhubProjectResponses[keyof UnlinkTenderhubProjectResponses];

export type TestTenderhubConnectionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/integrations/tenderhub/test-connection';
};

export type TestTenderhubConnectionResponses = {
    /**
     * Successful Response
     */
    200: TenderHubProbeRead;
};

export type TestTenderhubConnectionResponse = TestTenderhubConnectionResponses[keyof TestTenderhubConnectionResponses];

export type ListAdminJobsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
        /**
         * Status
         *
         * Фильтр по состоянию
         */
        status?: JobStatus | null;
        /**
         * Job Type
         *
         * Фильтр по типу
         */
        job_type?: JobType | null;
        /**
         * Project Id
         *
         * Фильтр по проекту
         */
        project_id?: string | null;
        /**
         * Scope
         *
         * Фильтр по области видимости
         */
        scope?: JobScope | null;
    };
    url: '/api/v1/admin/jobs';
};

export type ListAdminJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListAdminJobsError = ListAdminJobsErrors[keyof ListAdminJobsErrors];

export type ListAdminJobsResponses = {
    /**
     * Successful Response
     */
    200: PageAdminJobRead;
};

export type ListAdminJobsResponse = ListAdminJobsResponses[keyof ListAdminJobsResponses];

export type ReadJobStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/jobs/stats';
};

export type ReadJobStatsResponses = {
    /**
     * Successful Response
     */
    200: JobStatsRead;
};

export type ReadJobStatsResponse = ReadJobStatsResponses[keyof ReadJobStatsResponses];

export type ListJobWorkersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/jobs/workers';
};

export type ListJobWorkersResponses = {
    /**
     * Response List Job Workers
     *
     * Successful Response
     */
    200: Array<WorkerRead>;
};

export type ListJobWorkersResponse = ListJobWorkersResponses[keyof ListJobWorkersResponses];

export type ReadAdminJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/admin/jobs/{job_id}';
};

export type ReadAdminJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadAdminJobError = ReadAdminJobErrors[keyof ReadAdminJobErrors];

export type ReadAdminJobResponses = {
    /**
     * Successful Response
     */
    200: AdminJobRead;
};

export type ReadAdminJobResponse = ReadAdminJobResponses[keyof ReadAdminJobResponses];

export type CancelAdminJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/admin/jobs/{job_id}/cancel';
};

export type CancelAdminJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelAdminJobError = CancelAdminJobErrors[keyof CancelAdminJobErrors];

export type CancelAdminJobResponses = {
    /**
     * Successful Response
     */
    200: AdminJobRead;
};

export type CancelAdminJobResponse = CancelAdminJobResponses[keyof CancelAdminJobResponses];

export type RetryAdminJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/admin/jobs/{job_id}/retry';
};

export type RetryAdminJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryAdminJobError = RetryAdminJobErrors[keyof RetryAdminJobErrors];

export type RetryAdminJobResponses = {
    /**
     * Successful Response
     */
    200: AdminJobRead;
};

export type RetryAdminJobResponse = RetryAdminJobResponses[keyof RetryAdminJobResponses];

export type ListModelProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/model-providers';
};

export type ListModelProvidersResponses = {
    /**
     * Response List Model Providers
     *
     * Successful Response
     */
    200: Array<ModelProviderRead>;
};

export type ListModelProvidersResponse = ListModelProvidersResponses[keyof ListModelProvidersResponses];

export type CheckModelProviderData = {
    body?: never;
    path: {
        /**
         * Provider Id
         */
        provider_id: string;
    };
    query?: never;
    url: '/api/v1/admin/model-providers/{provider_id}/health-check';
};

export type CheckModelProviderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckModelProviderError = CheckModelProviderErrors[keyof CheckModelProviderErrors];

export type CheckModelProviderResponses = {
    /**
     * Successful Response
     */
    200: ModelProviderProbeRead;
};

export type CheckModelProviderResponse = CheckModelProviderResponses[keyof CheckModelProviderResponses];

export type ListSettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/admin/settings';
};

export type ListSettingsResponses = {
    /**
     * Response List Settings
     *
     * Successful Response
     */
    200: Array<SettingStateRead>;
};

export type ListSettingsResponse = ListSettingsResponses[keyof ListSettingsResponses];

export type DeleteSettingOverrideData = {
    body?: never;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query: {
        /**
         * С какого уровня снять
         */
        scope: OverrideScope;
    };
    url: '/api/v1/admin/settings/{key}';
};

export type DeleteSettingOverrideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSettingOverrideError = DeleteSettingOverrideErrors[keyof DeleteSettingOverrideErrors];

export type DeleteSettingOverrideResponses = {
    /**
     * Successful Response
     */
    200: SettingStateRead;
};

export type DeleteSettingOverrideResponse = DeleteSettingOverrideResponses[keyof DeleteSettingOverrideResponses];

export type SetSettingOverrideData = {
    body: SettingOverrideWrite;
    path: {
        /**
         * Key
         */
        key: string;
    };
    query?: never;
    url: '/api/v1/admin/settings/{key}';
};

export type SetSettingOverrideErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetSettingOverrideError = SetSettingOverrideErrors[keyof SetSettingOverrideErrors];

export type SetSettingOverrideResponses = {
    /**
     * Successful Response
     */
    200: SettingStateRead;
};

export type SetSettingOverrideResponse = SetSettingOverrideResponses[keyof SetSettingOverrideResponses];

export type CompleteLoginData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Code
         *
         * Код авторизации провайдера
         */
        code: string;
        /**
         * State
         *
         * Значение состояния
         */
        state: string;
    };
    url: '/api/v1/auth/callback';
};

export type CompleteLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompleteLoginError = CompleteLoginErrors[keyof CompleteLoginErrors];

export type BeginLoginData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Next
         *
         * Путь внутри портала
         */
        next?: string | null;
    };
    url: '/api/v1/auth/login';
};

export type BeginLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BeginLoginError = BeginLoginErrors[keyof BeginLoginErrors];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: LogoutResponse;
};

export type LogoutResponse2 = LogoutResponses[keyof LogoutResponses];

export type ReadSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/session';
};

export type ReadSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionResponse;
};

export type ReadSessionResponse = ReadSessionResponses[keyof ReadSessionResponses];

export type ReadDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/api/v1/documents/{document_id}';
};

export type ReadDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadDocumentError = ReadDocumentErrors[keyof ReadDocumentErrors];

export type ReadDocumentResponses = {
    /**
     * Successful Response
     */
    200: DocumentRead;
};

export type ReadDocumentResponse = ReadDocumentResponses[keyof ReadDocumentResponses];

export type ListDocumentRevisionsData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
    };
    url: '/api/v1/documents/{document_id}/revisions';
};

export type ListDocumentRevisionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDocumentRevisionsError = ListDocumentRevisionsErrors[keyof ListDocumentRevisionsErrors];

export type ListDocumentRevisionsResponses = {
    /**
     * Successful Response
     */
    200: PageDocumentRevisionRead;
};

export type ListDocumentRevisionsResponse = ListDocumentRevisionsResponses[keyof ListDocumentRevisionsResponses];

export type ImportTenderData = {
    body: TenderImport;
    path?: never;
    query?: never;
    url: '/api/v1/integrations/tenderhub/projects';
};

export type ImportTenderErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ImportTenderError = ImportTenderErrors[keyof ImportTenderErrors];

export type ImportTenderResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type ImportTenderResponse = ImportTenderResponses[keyof ImportTenderResponses];

export type ListTendersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/api/v1/integrations/tenderhub/tenders';
};

export type ListTendersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTendersError = ListTendersErrors[keyof ListTendersErrors];

export type ListTendersResponses = {
    /**
     * Response List Tenders
     *
     * Successful Response
     */
    200: Array<TenderBriefRead>;
};

export type ListTendersResponse = ListTendersResponses[keyof ListTendersResponses];

export type ReadJobData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/v1/jobs/{job_id}';
};

export type ReadJobErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadJobError = ReadJobErrors[keyof ReadJobErrors];

export type ReadJobResponses = {
    /**
     * Successful Response
     */
    200: JobRead;
};

export type ReadJobResponse = ReadJobResponses[keyof ReadJobResponses];

export type ReadMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/meta';
};

export type ReadMetaResponses = {
    /**
     * Successful Response
     */
    200: MetaResponse;
};

export type ReadMetaResponse = ReadMetaResponses[keyof ReadMetaResponses];

export type ListProjectsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
        /**
         * Search
         */
        search?: string | null;
        sort?: ProjectSort;
    };
    url: '/api/v1/projects';
};

export type ListProjectsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectsError = ListProjectsErrors[keyof ListProjectsErrors];

export type ListProjectsResponses = {
    /**
     * Successful Response
     */
    200: PageProjectSummary;
};

export type ListProjectsResponse = ListProjectsResponses[keyof ListProjectsResponses];

export type CreateProjectData = {
    body: ProjectCreate;
    path?: never;
    query?: never;
    url: '/api/v1/projects';
};

export type CreateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProjectError = CreateProjectErrors[keyof CreateProjectErrors];

export type CreateProjectResponses = {
    /**
     * Successful Response
     */
    201: ProjectRead;
};

export type CreateProjectResponse = CreateProjectResponses[keyof CreateProjectResponses];

export type ReadProjectData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type ReadProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadProjectError = ReadProjectErrors[keyof ReadProjectErrors];

export type ReadProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectSummary;
};

export type ReadProjectResponse = ReadProjectResponses[keyof ReadProjectResponses];

export type UpdateProjectData = {
    body: ProjectUpdate;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}';
};

export type UpdateProjectErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProjectError = UpdateProjectErrors[keyof UpdateProjectErrors];

export type UpdateProjectResponses = {
    /**
     * Successful Response
     */
    200: ProjectRead;
};

export type UpdateProjectResponse = UpdateProjectResponses[keyof UpdateProjectResponses];

export type ListProjectDocumentsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
    };
    url: '/api/v1/projects/{project_id}/documents';
};

export type ListProjectDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectDocumentsError = ListProjectDocumentsErrors[keyof ListProjectDocumentsErrors];

export type ListProjectDocumentsResponses = {
    /**
     * Successful Response
     */
    200: PageDocumentRead;
};

export type ListProjectDocumentsResponse = ListProjectDocumentsResponses[keyof ListProjectDocumentsResponses];

export type ListProjectJobsData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
    };
    url: '/api/v1/projects/{project_id}/jobs';
};

export type ListProjectJobsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListProjectJobsError = ListProjectJobsErrors[keyof ListProjectJobsErrors];

export type ListProjectJobsResponses = {
    /**
     * Successful Response
     */
    200: PageJobRead;
};

export type ListProjectJobsResponse = ListProjectJobsResponses[keyof ListProjectJobsResponses];

export type ReadUploadCapabilitiesData = {
    body?: never;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/upload-capabilities';
};

export type ReadUploadCapabilitiesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadUploadCapabilitiesError = ReadUploadCapabilitiesErrors[keyof ReadUploadCapabilitiesErrors];

export type ReadUploadCapabilitiesResponses = {
    /**
     * Response Read Upload Capabilities
     *
     * Successful Response
     */
    200: Array<UploadedFileType>;
};

export type ReadUploadCapabilitiesResponse = ReadUploadCapabilitiesResponses[keyof ReadUploadCapabilitiesResponses];

export type UploadFileData = {
    body: BodyUploadFile;
    path: {
        /**
         * Project Id
         */
        project_id: string;
    };
    query?: never;
    url: '/api/v1/projects/{project_id}/uploads';
};

export type UploadFileErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileError = UploadFileErrors[keyof UploadFileErrors];

export type UploadFileResponses = {
    /**
     * Successful Response
     */
    201: UploadRead;
};

export type UploadFileResponse = UploadFileResponses[keyof UploadFileResponses];

export type ReadRevisionData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query?: never;
    url: '/api/v1/revisions/{revision_id}';
};

export type ReadRevisionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRevisionError = ReadRevisionErrors[keyof ReadRevisionErrors];

export type ReadRevisionResponses = {
    /**
     * Successful Response
     */
    200: DocumentRevisionRead;
};

export type ReadRevisionResponse = ReadRevisionResponses[keyof ReadRevisionResponses];

export type ListRevisionArtifactsData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query?: never;
    url: '/api/v1/revisions/{revision_id}/artifacts';
};

export type ListRevisionArtifactsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRevisionArtifactsError = ListRevisionArtifactsErrors[keyof ListRevisionArtifactsErrors];

export type ListRevisionArtifactsResponses = {
    /**
     * Response List Revision Artifacts
     *
     * Successful Response
     */
    200: Array<RecognitionArtifactRead>;
};

export type ListRevisionArtifactsResponse = ListRevisionArtifactsResponses[keyof ListRevisionArtifactsResponses];

export type ReadRevisionContentUrlData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query?: never;
    url: '/api/v1/revisions/{revision_id}/content-url';
};

export type ReadRevisionContentUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadRevisionContentUrlError = ReadRevisionContentUrlErrors[keyof ReadRevisionContentUrlErrors];

export type ReadRevisionContentUrlResponses = {
    /**
     * Successful Response
     */
    200: ContentUrl;
};

export type ReadRevisionContentUrlResponse = ReadRevisionContentUrlResponses[keyof ReadRevisionContentUrlResponses];

export type ListRevisionSheetsData = {
    body?: never;
    path: {
        /**
         * Revision Id
         */
        revision_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
    };
    url: '/api/v1/revisions/{revision_id}/sheets';
};

export type ListRevisionSheetsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListRevisionSheetsError = ListRevisionSheetsErrors[keyof ListRevisionSheetsErrors];

export type ListRevisionSheetsResponses = {
    /**
     * Successful Response
     */
    200: PageSheetRead;
};

export type ListRevisionSheetsResponse = ListRevisionSheetsResponses[keyof ListRevisionSheetsResponses];

export type ReadCalibrationData = {
    body?: never;
    path: {
        /**
         * Calibration Id
         */
        calibration_id: string;
    };
    query?: never;
    url: '/api/v1/scale-calibrations/{calibration_id}';
};

export type ReadCalibrationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadCalibrationError = ReadCalibrationErrors[keyof ReadCalibrationErrors];

export type ReadCalibrationResponses = {
    /**
     * Successful Response
     */
    200: ScaleCalibrationRead;
};

export type ReadCalibrationResponse = ReadCalibrationResponses[keyof ReadCalibrationResponses];

export type MakeCalibrationDefaultData = {
    body?: never;
    path: {
        /**
         * Calibration Id
         */
        calibration_id: string;
    };
    query?: never;
    url: '/api/v1/scale-calibrations/{calibration_id}/default';
};

export type MakeCalibrationDefaultErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type MakeCalibrationDefaultError = MakeCalibrationDefaultErrors[keyof MakeCalibrationDefaultErrors];

export type MakeCalibrationDefaultResponses = {
    /**
     * Successful Response
     */
    200: ScaleCalibrationRead;
};

export type MakeCalibrationDefaultResponse = MakeCalibrationDefaultResponses[keyof MakeCalibrationDefaultResponses];

export type SetCalibrationVerificationData = {
    body: ScaleVerificationWrite;
    path: {
        /**
         * Calibration Id
         */
        calibration_id: string;
    };
    query?: never;
    url: '/api/v1/scale-calibrations/{calibration_id}/verification';
};

export type SetCalibrationVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SetCalibrationVerificationError = SetCalibrationVerificationErrors[keyof SetCalibrationVerificationErrors];

export type SetCalibrationVerificationResponses = {
    /**
     * Successful Response
     */
    200: ScaleCalibrationRead;
};

export type SetCalibrationVerificationResponse = SetCalibrationVerificationResponses[keyof SetCalibrationVerificationResponses];

export type ReadSheetGeometryData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: never;
    url: '/api/v1/sheets/{sheet_id}/geometry';
};

export type ReadSheetGeometryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadSheetGeometryError = ReadSheetGeometryErrors[keyof ReadSheetGeometryErrors];

export type ReadSheetGeometryResponses = {
    /**
     * Successful Response
     */
    200: PageGeometryRead;
};

export type ReadSheetGeometryResponse = ReadSheetGeometryResponses[keyof ReadSheetGeometryResponses];

export type ListSheetRegionsData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: {
        /**
         * Limit
         *
         * Сколько записей вернуть
         */
        limit?: number;
        /**
         * Offset
         *
         * Сколько записей пропустить
         */
        offset?: number;
        /**
         * Block Type
         *
         * Фильтр по типу области
         */
        block_type?: string | null;
        /**
         * Recognition Status
         *
         * Фильтр по статусу распознавания
         */
        recognition_status?: string | null;
    };
    url: '/api/v1/sheets/{sheet_id}/regions';
};

export type ListSheetRegionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSheetRegionsError = ListSheetRegionsErrors[keyof ListSheetRegionsErrors];

export type ListSheetRegionsResponses = {
    /**
     * Successful Response
     */
    200: PageRegionRead;
};

export type ListSheetRegionsResponse = ListSheetRegionsResponses[keyof ListSheetRegionsResponses];

export type ListSheetCalibrationsData = {
    body?: never;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: never;
    url: '/api/v1/sheets/{sheet_id}/scale-calibrations';
};

export type ListSheetCalibrationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSheetCalibrationsError = ListSheetCalibrationsErrors[keyof ListSheetCalibrationsErrors];

export type ListSheetCalibrationsResponses = {
    /**
     * Response List Sheet Calibrations
     *
     * Successful Response
     */
    200: Array<ScaleCalibrationRead>;
};

export type ListSheetCalibrationsResponse = ListSheetCalibrationsResponses[keyof ListSheetCalibrationsResponses];

export type CreateSheetCalibrationData = {
    body: ScaleCalibrationCreate;
    path: {
        /**
         * Sheet Id
         */
        sheet_id: string;
    };
    query?: never;
    url: '/api/v1/sheets/{sheet_id}/scale-calibrations';
};

export type CreateSheetCalibrationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSheetCalibrationError = CreateSheetCalibrationErrors[keyof CreateSheetCalibrationErrors];

export type CreateSheetCalibrationResponses = {
    /**
     * Successful Response
     */
    201: ScaleCalibrationRead;
};

export type CreateSheetCalibrationResponse = CreateSheetCalibrationResponses[keyof CreateSheetCalibrationResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type LivenessResponse2 = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadinessResponse2 = ReadinessResponses[keyof ReadinessResponses];
