// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ComponentHealth
 */
export type ComponentHealth = {
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Name
     */
    name: string;
    /**
     * Status
     */
    status: 'ok' | 'unavailable';
};

/**
 * LivenessResponse
 */
export type LivenessResponse = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * MetaResponse
 */
export type MetaResponse = {
    /**
     * Api Version
     */
    api_version: string;
    /**
     * Environment
     */
    environment: string;
    /**
     * Features
     */
    features: {
        [key: string]: boolean;
    };
    /**
     * Schema Version
     */
    schema_version: number;
    /**
     * Stage
     */
    stage: string;
};

/**
 * ReadinessResponse
 */
export type ReadinessResponse = {
    /**
     * Components
     */
    components: Array<ComponentHealth>;
    /**
     * Status
     */
    status: 'ok' | 'degraded';
};

export type ReadMetaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/meta';
};

export type ReadMetaResponses = {
    /**
     * Successful Response
     */
    200: MetaResponse;
};

export type ReadMetaResponse = ReadMetaResponses[keyof ReadMetaResponses];

export type LivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type LivenessResponses = {
    /**
     * Successful Response
     */
    200: LivenessResponse;
};

export type LivenessResponse2 = LivenessResponses[keyof LivenessResponses];

export type ReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type ReadinessResponses = {
    /**
     * Successful Response
     */
    200: ReadinessResponse;
};

export type ReadinessResponse2 = ReadinessResponses[keyof ReadinessResponses];
