"""Каталог исходных данных ВК стадии П: что понадобится калькулятору В1, Т3, Т4, К1 (PROMPT 02).

Каталог живёт рядом с будущим калькулятором (PROMPT 06) и версионируется вместе с ним. Это
декларация, а не расчёт: здесь нет ни одного коэффициента и ни одного правила — только
«какое данное нужно, насколько, где его обычно искать и можно ли его вывести или допустить».

Требования с областью SYSTEM относятся к той системе, для которой строится матрица: один и тот
же «материал трубопроводов» — свой у В1 и свой у К1.
"""

from __future__ import annotations

from typing import Final

from app.contracts.calc.enums import (
    CalcAssumptionPolicy,
    CalcDiscipline,
    CalcRequirementGroup,
    CalcRequirementLevel,
    CalcRequirementScope,
    CalcSourceClass,
)
from app.contracts.calc.requirements import CalcInputRequirement, CalcSystemDef

VK_REQUIREMENTS_VERSION: Final = "calc.requirements.vk.v1"

VK_SYSTEMS: Final[tuple[CalcSystemDef, ...]] = (
    CalcSystemDef(CalcDiscipline.VK, "В1", "Хозяйственно-питьевой водопровод"),
    CalcSystemDef(CalcDiscipline.VK, "Т3", "Горячее водоснабжение, подающий"),
    CalcSystemDef(CalcDiscipline.VK, "Т4", "Горячее водоснабжение, циркуляционный"),
    CalcSystemDef(CalcDiscipline.VK, "К1", "Бытовая канализация"),
)

_ALL = ("В1", "Т3", "Т4", "К1")
_WATER = ("В1", "Т3", "Т4")
_HOT = ("Т3", "Т4")
_DRINKING_HOT_SEWER = ("В1", "Т3", "К1")

_G = CalcRequirementGroup
_S = CalcRequirementScope
_L = CalcRequirementLevel
_A = CalcAssumptionPolicy
_C = CalcSourceClass


def _req(
    id_: str,
    title: str,
    group: CalcRequirementGroup,
    fact_type: str,
    scope: CalcRequirementScope,
    level: CalcRequirementLevel,
    assumption: CalcAssumptionPolicy,
    description: str,
    systems: tuple[str, ...],
    *,
    derivable_from: tuple[str, ...] = (),
    sources: tuple[CalcSourceClass, ...] = (),
    manual_when_absent: bool = False,
) -> CalcInputRequirement:
    return CalcInputRequirement(
        id=id_,
        title=title,
        group=group,
        fact_type=fact_type,
        scope=scope,
        level=level,
        assumption=assumption,
        description=description,
        systems=systems,
        derivable_from=derivable_from,
        expected_sources=sources,
        manual_when_sources_absent=manual_when_absent,
    )


VK_REQUIREMENTS: Final[tuple[CalcInputRequirement, ...]] = (
    # ---- геометрия объекта ------------------------------------------------------------------
    _req(
        "vk.building.sections",
        "Секции",
        _G.GEOMETRY,
        "building.sections_count",
        _S.BUILDING,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Секции задают группы стояков и вводов: без них стояки не распределить по дому.",
        _ALL,
        sources=(_C.ARCHITECTURE, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.building.floors_above",
        "Этажность",
        _G.GEOMETRY,
        "building.floors_above_ground",
        _S.BUILDING,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Надземные этажи определяют высоту стояков и число зон по давлению.",
        _ALL,
        sources=(_C.ARCHITECTURE, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.building.floors_below",
        "Подземные этажи",
        _G.GEOMETRY,
        "building.floors_below_ground",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.MANUAL,
        "Под землёй проходят магистрали и выпуски.",
        _ALL,
        sources=(_C.ARCHITECTURE, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.building.basement",
        "Подвал или техподполье",
        _G.GEOMETRY,
        "building.basement_type",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.MANUAL,
        "Нижняя разводка магистралей В1, Т3, Т4 и сборных трубопроводов К1.",
        _ALL,
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.building.top_space",
        "Технический этаж или чердак",
        _G.GEOMETRY,
        "building.top_technical_space",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.MANUAL,
        "Верхняя разводка, кольцевание Т3 и Т4, выпуск воздуха из систем.",
        _WATER,
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.building.roof",
        "Тип кровли",
        _G.GEOMETRY,
        "building.roof_type",
        _S.BUILDING,
        _L.OPTIONAL,
        _A.MANUAL,
        "Вытяжная часть канализационных стояков выводится через кровлю.",
        ("К1",),
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.building.zero_abs",
        "Абсолютная отметка ±0,000",
        _G.GEOMETRY,
        "building.elevation_zero_abs",
        _S.BUILDING,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Связывает напор из ТУ и отметки выпусков с высотами здания.",
        ("В1", "К1"),
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.building.height",
        "Высота здания",
        _G.GEOMETRY,
        "building.height",
        _S.BUILDING,
        _L.DERIVABLE,
        _A.REGISTERED_RULE,
        "Высота задаёт зоны по давлению; выводится из отметок и высот этажей.",
        _WATER,
        derivable_from=("floor.elevation", "floor.height"),
        sources=(_C.ARCHITECTURE, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.floor.height",
        "Высоты этажей",
        _G.GEOMETRY,
        "floor.height",
        _S.FLOOR,
        _L.REQUIRED,
        _A.MANUAL,
        "Высоты этажей дают длины стояков.",
        _ALL,
        derivable_from=("floor.elevation",),
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.floor.elevation",
        "Отметки этажей",
        _G.GEOMETRY,
        "floor.elevation",
        _S.FLOOR,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Отметки из названий планов; из них выводятся высоты этажей.",
        _ALL,
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.floor.function",
        "Назначение этажей",
        _G.GEOMETRY,
        "floor.function",
        _S.FLOOR,
        _L.REQUIRED,
        _A.MANUAL,
        "Где квартиры, где коммерция и технические этажи — от этого зависят подключения.",
        _ALL,
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.floor.corridor",
        "Длины коридоров МОП",
        _G.GEOMETRY,
        "floor.corridor_length",
        _S.FLOOR,
        _L.DESIRABLE,
        _A.MANUAL,
        "Поэтажная разводка от стояков в МОП до квартир при коридорной схеме.",
        ("В1", "Т3"),
        sources=(_C.ARCHITECTURE,),
    ),
    _req(
        "vk.floor.shafts",
        "Шахты и ниши ВК",
        _G.GEOMETRY,
        "floor.shafts_count",
        _S.FLOOR,
        _L.DESIRABLE,
        _A.MANUAL,
        "Вертикальные шахты задают число стояков и поэтажных узлов.",
        _ALL,
        sources=(_C.ARCHITECTURE, _C.MEP_DESIGN),
    ),
    _req(
        "vk.system.risers",
        "Стояки системы",
        _G.GEOMETRY,
        "system.risers_count",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Число стояков по схемам П; если схем нет — из шахт и квартирографии.",
        _ALL,
        derivable_from=("floor.shafts_count", "floor.apartments_count"),
        sources=(_C.MEP_DESIGN,),
    ),
    # ---- квартирография ---------------------------------------------------------------------
    _req(
        "vk.apartments.total",
        "Всего квартир",
        _G.APARTMENTS,
        "building.apartments_total",
        _S.BUILDING,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Квартиры — потребители и поквартирные узлы учёта.",
        _ALL,
        derivable_from=("floor.apartments_count",),
        sources=(_C.APARTMENT_SCHEDULE, _C.ARCHITECTURE, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.apartments.per_floor",
        "Квартиры на этажах",
        _G.APARTMENTS,
        "floor.apartments_count",
        _S.FLOOR,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Поэтажные подключения и нагрузка на стояки.",
        _ALL,
        sources=(_C.APARTMENT_SCHEDULE, _C.ARCHITECTURE),
    ),
    _req(
        "vk.apartments.types",
        "Типы квартир",
        _G.APARTMENTS,
        "building.apartments_by_type",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.NOT_ALLOWED,
        "Тип квартиры задаёт набор санприборов и число жителей.",
        _ALL,
        sources=(_C.APARTMENT_SCHEDULE,),
    ),
    _req(
        "vk.apartments.kitchens",
        "Кухни",
        _G.APARTMENTS,
        "floor.kitchens_count",
        _S.FLOOR,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Мойки на кухнях — точки В1, Т3 и К1.",
        _DRINKING_HOT_SEWER,
        derivable_from=("floor.apartments_count",),
        sources=(_C.APARTMENT_SCHEDULE, _C.ROOM_SCHEDULE),
    ),
    _req(
        "vk.apartments.bathrooms",
        "Санузлы и ванные",
        _G.APARTMENTS,
        "floor.bathrooms_count",
        _S.FLOOR,
        _L.REQUIRED,
        _A.REGISTERED_RULE,
        "Основная доля приборов и стояков К1; полотенцесушители Т3 и Т4.",
        _ALL,
        derivable_from=("building.apartments_by_type",),
        sources=(_C.APARTMENT_SCHEDULE, _C.ROOM_SCHEDULE),
    ),
    _req(
        "vk.apartments.fixtures",
        "Санитарные приборы",
        _G.APARTMENTS,
        "building.fixtures_count",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Приборы по видам определяют расходы воды и стоков.",
        _DRINKING_HOT_SEWER,
        derivable_from=("floor.bathrooms_count", "floor.kitchens_count"),
        sources=(_C.FIXTURE_TABLE, _C.MEP_DESIGN),
    ),
    _req(
        "vk.apartments.residents",
        "Число жителей",
        _G.APARTMENTS,
        "building.residents_count",
        _S.BUILDING,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Жители — потребители в суточном и часовом расходе.",
        ("В1", "Т3"),
        derivable_from=("building.apartments_by_type",),
        sources=(_C.EXPLANATORY_NOTE, _C.APARTMENT_SCHEDULE),
    ),
    # ---- нежилые помещения ------------------------------------------------------------------
    _req(
        "vk.nonres.commercial",
        "Встроенные помещения",
        _G.NONRESIDENTIAL,
        "floor.commercial_units_count",
        _S.FLOOR,
        _L.DESIRABLE,
        _A.MANUAL,
        "Коммерция и общественные помещения: свои вводы или узлы учёта, отдельные выпуски К1.",
        _DRINKING_HOT_SEWER,
        sources=(_C.ARCHITECTURE, _C.ROOM_SCHEDULE),
    ),
    _req(
        "vk.nonres.wet_rooms",
        "Помещения с водой вне квартир",
        _G.NONRESIDENTIAL,
        "floor.nonresidential_wet_rooms_count",
        _S.FLOOR,
        _L.DESIRABLE,
        _A.MANUAL,
        "ПУИ, санузлы персонала и общественных зон, душевые, моечные — точки МОП и коммерции.",
        _DRINKING_HOT_SEWER,
        sources=(_C.ROOM_SCHEDULE,),
    ),
    # ---- водоснабжение ----------------------------------------------------------------------
    _req(
        "vk.water.present",
        "Система предусмотрена",
        _G.WATER_SUPPLY,
        "system.present",
        _S.SYSTEM,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Предусмотрена ли система проектом П: без этого систему не считают.",
        _WATER,
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.b1.inlet_pressure",
        "Гарантированный напор",
        _G.WATER_SUPPLY,
        "system.inlet_pressure",
        _S.SYSTEM,
        _L.REQUIRED,
        _A.MANUAL,
        "Напор в точке подключения по ТУ: нужны ли насосы и сколько зон по давлению.",
        ("В1",),
        sources=(_C.TECHNICAL_CONDITIONS,),
        manual_when_absent=True,
    ),
    _req(
        "vk.b1.inlets",
        "Вводы",
        _G.WATER_SUPPLY,
        "system.inlets_count",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.MANUAL,
        "Число вводов: узлы учёта и трассы от вводов до насосной.",
        ("В1",),
        sources=(_C.TECHNICAL_CONDITIONS, _C.MEP_DESIGN),
    ),
    _req(
        "vk.b1.inlet_diameter",
        "Диаметр ввода",
        _G.WATER_SUPPLY,
        "system.inlet_diameter",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Диаметр ввода, если его задают ТУ или проект.",
        ("В1",),
        sources=(_C.TECHNICAL_CONDITIONS, _C.MEP_DESIGN),
    ),
    _req(
        "vk.water.zones",
        "Зоны по давлению",
        _G.WATER_SUPPLY,
        "system.zones_count",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Зоны системы по давлению; выводятся из высоты здания и напора.",
        _WATER,
        derivable_from=("building.height", "system.inlet_pressure"),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.b1.pumps",
        "Насосная установка",
        _G.WATER_SUPPLY,
        "system.pump_station_present",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.REGISTERED_RULE,
        "Нужна ли насосная установка повышения давления.",
        ("В1",),
        derivable_from=("system.inlet_pressure", "building.height"),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.water.meters",
        "Узлы учёта",
        _G.WATER_SUPPLY,
        "system.water_meter_units_count",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.REGISTERED_RULE,
        "Общий узел на вводе и поквартирные узлы учёта.",
        ("В1", "Т3"),
        derivable_from=("building.apartments_total", "system.inlets_count"),
        sources=(_C.MEP_DESIGN,),
    ),
    _req(
        "vk.water.material",
        "Материал трубопроводов",
        _G.WATER_SUPPLY,
        "system.pipe_material",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.MANUAL,
        "Материал задаёт сортамент труб и фитингов.",
        _WATER,
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE, _C.BRAND_LIST),
    ),
    _req(
        "vk.water.flow_daily",
        "Суточный расход по проекту",
        _G.WATER_SUPPLY,
        "system.flow_daily",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Расход проекта — для сверки с расчётом Quantor, а не вместо него.",
        ("В1", "Т3"),
        sources=(_C.EXPLANATORY_NOTE, _C.MEP_DESIGN),
    ),
    _req(
        "vk.water.flow_hourly",
        "Часовой расход по проекту",
        _G.WATER_SUPPLY,
        "system.flow_hourly_max",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Максимальный часовой расход проекта — для сверки.",
        ("В1", "Т3"),
        sources=(_C.EXPLANATORY_NOTE, _C.MEP_DESIGN),
    ),
    _req(
        "vk.water.flow_second",
        "Секундный расход по проекту",
        _G.WATER_SUPPLY,
        "system.flow_second_max",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Максимальный секундный расход проекта — для сверки.",
        ("В1", "Т3"),
        sources=(_C.EXPLANATORY_NOTE, _C.MEP_DESIGN),
    ),
    _req(
        "vk.t3.source",
        "Источник горячей воды",
        _G.WATER_SUPPLY,
        "system.hot_water_source",
        _S.SYSTEM,
        _L.REQUIRED,
        _A.MANUAL,
        "Где начинаются Т3 и Т4: ИТП, ЦТП, котельная или водонагреватели.",
        ("Т3",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE, _C.TECHNICAL_CONDITIONS),
    ),
    _req(
        "vk.t3.temperature",
        "Температура горячей воды",
        _G.WATER_SUPPLY,
        "system.supply_temperature",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.REGISTERED_RULE,
        "Если проект её не указывает, значение даст правило реестра, а не умолчание.",
        ("Т3",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.hot.towel_dryers",
        "Полотенцесушители от ГВС",
        _G.WATER_SUPPLY,
        "system.towel_dryers_on_hot_water",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.MANUAL,
        "Полотенцесушители на стояках Т3 и Т4 меняют кольцевание и число стояков.",
        _HOT,
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.water.main_diameter",
        "Диаметры магистралей",
        _G.WATER_SUPPLY,
        "system.main_diameter",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Известные диаметры магистралей по схемам П уточняют подбор.",
        _WATER,
        sources=(_C.MEP_DESIGN,),
    ),
    _req(
        "vk.water.riser_diameter",
        "Диаметры стояков",
        _G.WATER_SUPPLY,
        "system.riser_diameter",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Известные диаметры стояков по схемам П уточняют подбор.",
        _WATER,
        sources=(_C.MEP_DESIGN,),
    ),
    # ---- канализация ------------------------------------------------------------------------
    _req(
        "vk.k1.present",
        "Система предусмотрена",
        _G.SEWERAGE,
        "system.present",
        _S.SYSTEM,
        _L.REQUIRED,
        _A.NOT_ALLOWED,
        "Предусмотрена ли система проектом П: без этого систему не считают.",
        ("К1",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.k1.outlets",
        "Выпуски",
        _G.SEWERAGE,
        "system.outlets_count",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.MANUAL,
        "Выпуски задают сборные трубопроводы и их длины.",
        ("К1",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.k1.outlet_diameter",
        "Диаметр выпуска",
        _G.SEWERAGE,
        "system.outlet_diameter",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Диаметр выпуска, если его задаёт проект.",
        ("К1",),
        sources=(_C.MEP_DESIGN,),
    ),
    _req(
        "vk.k1.outlet_elevation",
        "Отметки выпусков",
        _G.SEWERAGE,
        "system.outlet_elevation",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Отметки лотков выпусков — длины и уклоны сборных трубопроводов.",
        ("К1",),
        sources=(_C.MEP_DESIGN,),
    ),
    _req(
        "vk.k1.vent",
        "Вентиляция стояков",
        _G.SEWERAGE,
        "system.vent_scheme",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.MANUAL,
        "Вытяжная часть через кровлю или вентиляционные клапаны.",
        ("К1",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE),
    ),
    _req(
        "vk.k1.material",
        "Материал трубопроводов",
        _G.SEWERAGE,
        "system.pipe_material",
        _S.SYSTEM,
        _L.DESIRABLE,
        _A.MANUAL,
        "Материал задаёт сортамент труб и фасонных частей.",
        ("К1",),
        sources=(_C.MEP_DESIGN, _C.EXPLANATORY_NOTE, _C.BRAND_LIST),
    ),
    _req(
        "vk.k1.riser_diameter",
        "Диаметры стояков",
        _G.SEWERAGE,
        "system.riser_diameter",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Известные диаметры стояков по схемам П уточняют подбор.",
        ("К1",),
        sources=(_C.MEP_DESIGN,),
    ),
    # ---- прочее -----------------------------------------------------------------------------
    _req(
        "vk.other.manufacturer",
        "Заданные производители",
        _G.OTHER,
        "system.required_manufacturer",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Бренд-лист и требования Заказчика ограничивают выбор оборудования и труб.",
        _ALL,
        sources=(_C.BRAND_LIST, _C.TECHNICAL_REQUIREMENTS),
    ),
    _req(
        "vk.other.requirements",
        "Требования Заказчика",
        _G.OTHER,
        "system.customer_requirements",
        _S.SYSTEM,
        _L.OPTIONAL,
        _A.NOT_ALLOWED,
        "Технические требования и ограничения Заказчика к системе.",
        _ALL,
        sources=(_C.TECHNICAL_REQUIREMENTS,),
    ),
)


def requirements_for(system_code: str) -> tuple[CalcInputRequirement, ...]:
    """Требования одной системы каталога — в порядке каталога."""
    return tuple(item for item in VK_REQUIREMENTS if system_code in item.systems)
